"""Tests verifying our easing + spring + stagger ports match Motion's source.

Reference values were generated by the canonical Motion / framer-motion JS
implementation. If a constant ever drifts here, our PPTX timing curves
will silently start to disagree with Motion's web behaviour — these tests
catch that.
"""
from __future__ import annotations

import math

import pytest

from megadeck.animations.choreography import (
    get_origin_index,
    materialise_stagger,
    stagger_delay,
)
from megadeck.animations.easing import (
    EASINGS,
    anticipate,
    back_in,
    back_in_out,
    back_out,
    circ_in,
    circ_in_out,
    circ_out,
    cubic_bezier,
    ease_in,
    ease_in_out,
    ease_out,
    get_easing,
    mirror_easing,
    reverse_easing,
    sample_curve,
    steps,
)
from megadeck.animations.spring import (
    DEFAULT_BOUNCE,
    DEFAULT_DAMPING,
    DEFAULT_STIFFNESS,
    Spring,
)


# ---------------------------------------------------------------------------
# Cubic-bezier — comment in Motion's source: cubicBezier(.17,.67,.83,.67)
# evaluated at 0.5 should be ≈ 0.627. Verify our port matches.
# ---------------------------------------------------------------------------

def test_cubic_bezier_matches_motion_reference() -> None:
    """Reference value from Motion's cubic-bezier.ts header comment."""
    ease_out_local = cubic_bezier(0.17, 0.67, 0.83, 0.67)
    assert ease_out_local(0.5) == pytest.approx(0.627, abs=0.005)


def test_cubic_bezier_endpoints() -> None:
    f = cubic_bezier(0.42, 0, 0.58, 1)
    assert f(0) == 0
    assert f(1) == 1


def test_cubic_bezier_linear_short_circuit() -> None:
    f = cubic_bezier(0.5, 0.5, 0.5, 0.5)
    for x in (0.0, 0.25, 0.5, 0.75, 1.0):
        assert f(x) == x


# ---------------------------------------------------------------------------
# Named easings
# ---------------------------------------------------------------------------

def test_ease_in_uses_motion_constants() -> None:
    """Motion: easeIn = cubicBezier(0.42, 0, 1, 1)"""
    assert ease_in(0) == 0
    assert ease_in(1) == 1
    # easeIn should accelerate slowly — at t=0.5, y < t.
    assert ease_in(0.5) < 0.5


def test_ease_out_inverts_ease_in() -> None:
    # easeOut at any t > 0 should be > t (decelerates).
    for t in (0.25, 0.5, 0.75):
        assert ease_out(t) > t


def test_ease_in_out_is_symmetric() -> None:
    # easeInOut should map t and 1-t to mirrored values.
    assert ease_in_out(0.5) == pytest.approx(0.5, abs=0.01)


# ---------------------------------------------------------------------------
# Modifiers
# ---------------------------------------------------------------------------

def test_reverse_easing_inverts() -> None:
    rev = reverse_easing(ease_in)
    for t in (0.1, 0.3, 0.5, 0.7, 0.9):
        assert rev(t) == pytest.approx(1 - ease_in(1 - t), abs=1e-9)


def test_mirror_easing_is_symmetric() -> None:
    m = mirror_easing(ease_in)
    # First half of easeInOut should equal half of easeIn at 2t.
    for t in (0.1, 0.25, 0.4):
        assert m(t) == pytest.approx(ease_in(2 * t) / 2, abs=1e-9)
    # Second half should mirror.
    for t in (0.6, 0.75, 0.9):
        assert m(t) == pytest.approx((2 - ease_in(2 * (1 - t))) / 2, abs=1e-9)


# ---------------------------------------------------------------------------
# Circ + back + anticipate — overshoot family
# ---------------------------------------------------------------------------

def test_circ_in_zero_one() -> None:
    assert circ_in(0) == pytest.approx(0, abs=1e-9)
    assert circ_in(1) == pytest.approx(1, abs=1e-9)


def test_back_out_overshoots() -> None:
    """`back-out` should briefly exceed 1 before settling at 1."""
    overshot = max(back_out(t) for t in (0.6, 0.7, 0.8, 0.9))
    assert overshot > 1.0  # the canonical bounce


def test_back_in_pulls_back_first() -> None:
    """`back-in` should briefly go *below* 0 before climbing."""
    pulled = min(back_in(t) for t in (0.05, 0.1, 0.15, 0.2))
    assert pulled < 0.0


def test_anticipate_endpoints() -> None:
    assert anticipate(0) == pytest.approx(0, abs=1e-9)
    assert anticipate(1) == 1


# ---------------------------------------------------------------------------
# Steps
# ---------------------------------------------------------------------------

def test_steps_end() -> None:
    f = steps(4, "end")
    # Motion semantics: at exactly the boundary the next step is selected
    # only at the very end.
    assert f(0.0) == 0.0
    assert f(0.24) == 0.0
    assert f(0.26) == 0.25
    assert f(0.99) == 0.75


def test_steps_start() -> None:
    f = steps(4, "start")
    assert f(0.001) == 0.25
    assert f(0.99) == 1.0


# ---------------------------------------------------------------------------
# Easings registry
# ---------------------------------------------------------------------------

def test_easings_dict_complete() -> None:
    """Every named easing exists in the registry — used by JSON theme parsers."""
    expected = {
        "linear", "ease", "ease-in", "ease-out", "ease-in-out",
        "circ-in", "circ-out", "circ-in-out",
        "back-in", "back-out", "back-in-out",
        "anticipate",
    }
    assert expected.issubset(set(EASINGS))


def test_get_easing_unknown_raises() -> None:
    with pytest.raises(ValueError):
        get_easing("this-easing-does-not-exist")


def test_sample_curve_endpoints() -> None:
    samples = sample_curve(ease_out, n_samples=10)
    assert samples[0] == (0.0, 0.0)
    assert samples[-1] == (1.0, 1.0)


# ---------------------------------------------------------------------------
# Spring physics — sanity-check against expected behaviour
# ---------------------------------------------------------------------------

def test_spring_origin_zero_target_one() -> None:
    s = Spring()
    assert s.position(0) == pytest.approx(0.0, abs=1e-9)


def test_spring_settles_at_target() -> None:
    """A long-running default spring should settle near target=1."""
    s = Spring()
    assert s.position(5000) == pytest.approx(1.0, abs=0.05)


def test_spring_visualduration_default() -> None:
    """Motion's default visualDuration=0.3s, bounce=0.3 → specific stiffness/damping.

    Reference values computed with Motion's `getSpringOptions({ visualDuration: 0.3,
    bounce: 0.3 })`:
        root = 2π / (0.3 * 1.2) = 17.453
        stiffness = root² ≈ 304.6
        damping = 2 * 0.7 * √304.6 ≈ 24.4
    """
    s = Spring.from_visual_duration(0.3, bounce=0.3)
    assert s.stiffness == pytest.approx(304.6, rel=0.01)
    assert s.damping == pytest.approx(24.4, rel=0.02)


def test_spring_underdamped_behaviour() -> None:
    """A very low-bounce (high-overshoot) spring should oscillate above 1."""
    s = Spring.from_visual_duration(0.4, bounce=0.6)
    overshot = max(s.position(t) for t in range(50, 800, 50))
    assert overshot > 1.0


def test_spring_overdamped_behaviour() -> None:
    """A heavily-damped (negative-bounce ~ damping_ratio > 1) spring should
    monotonically approach the target without overshoot."""
    s = Spring(stiffness=100, damping=30, mass=1)  # damping ratio 1.5
    assert s.damping_ratio > 1
    last = -1.0
    for t in range(20, 2000, 20):
        cur = s.position(t)
        assert cur >= last - 1e-6
        last = cur


def test_spring_sample_returns_keyframes() -> None:
    s = Spring.from_visual_duration(0.3, 0.3)
    samples = s.sample(n_samples=20, duration_ms=600)
    assert len(samples) == 21
    assert samples[0].t_ms == 0.0
    assert samples[-1].t_ms == 600.0


def test_spring_from_duration_recovers_constants() -> None:
    """Spring.from_duration with the defaults should give back roughly the
    canonical spring constants."""
    s = Spring.from_duration(duration_ms=800, bounce=0.3)
    # Reference: Motion's findSpring({duration:800, bounce:0.3, mass:1, velocity:0})
    # converges on stiffness ≈ 75-90, damping ≈ 15-18 depending on the seed.
    assert 30 <= s.stiffness <= 200
    assert 5 <= s.damping <= 30


# ---------------------------------------------------------------------------
# Stagger / choreography
# ---------------------------------------------------------------------------

def test_get_origin_index_first_last_center() -> None:
    assert get_origin_index("first", 5) == 0
    assert get_origin_index("last", 5) == 4
    assert get_origin_index("center", 5) == 2.0
    assert get_origin_index("center", 6) == 2.5


def test_stagger_delay_first_origin() -> None:
    fn = stagger_delay(duration_s=0.1, origin="first")
    assert fn(0, 5) == pytest.approx(0.0)
    assert fn(2, 5) == pytest.approx(0.2)
    assert fn(4, 5) == pytest.approx(0.4)


def test_stagger_delay_last_origin_inverts_order() -> None:
    fn = stagger_delay(duration_s=0.1, origin="last")
    # last item has zero delay, first item has the most
    assert fn(4, 5) == pytest.approx(0.0)
    assert fn(0, 5) == pytest.approx(0.4)


def test_stagger_delay_center_ripples_outward() -> None:
    fn = stagger_delay(duration_s=0.1, origin="center")
    # 5 items → center is index 2; items 1+3 fire at +0.1, 0+4 at +0.2
    assert fn(2, 5) == pytest.approx(0.0)
    assert fn(1, 5) == pytest.approx(0.1)
    assert fn(3, 5) == pytest.approx(0.1)
    assert fn(0, 5) == pytest.approx(0.2)
    assert fn(4, 5) == pytest.approx(0.2)


def test_stagger_delay_with_easing_remaps() -> None:
    """When an easing is supplied, the *delays themselves* get eased.
    A back-out easing on a 5-shape stagger should make the early shapes
    fire faster (negative bezier overshoot) than linear."""
    linear = stagger_delay(duration_s=0.1, origin="first")
    eased = stagger_delay(duration_s=0.1, origin="first", easing="back-out")
    # Linear: index 1 fires at 0.1
    assert linear(1, 5) == pytest.approx(0.1)
    # Eased: should *not* be exactly 0.1.
    assert eased(1, 5) != pytest.approx(0.1, abs=1e-6)


def test_materialise_stagger_returns_list_of_delays() -> None:
    delays = materialise_stagger(4, duration_s=0.05)
    assert delays == pytest.approx([0.0, 0.05, 0.10, 0.15], abs=1e-9)


def test_materialise_stagger_zero_children() -> None:
    assert materialise_stagger(0) == []
