"""Example: build a 5-slide deck programmatically (no LLM required).

This is the same fixture used by the test suite. It demonstrates every
template, the speaker-notes attachment, and the section-divider chrome.

Run it from the repo root:

    python examples/build_sample_deck.py
"""
from __future__ import annotations

from pathlib import Path

from megadeck import render_deck
from megadeck.core.schemas import (
    BulletItem,
    CardItem,
    Deck,
    HeroStatementSlide,
    NumberedListSlide,
    SectionDividerSlide,
    ThreeCardSlide,
    TwoColumnSlide,
    TransitionKind,
)


def build_sample_deck() -> Deck:
    return Deck(
        title="Megadeck Demo",
        author="Orkhan Javadli",
        theme="default",
        slides=[
            SectionDividerSlide(
                kind="section_divider",
                part_label="Part 1",
                title="Megadeck Demo",
                subtitle="A 5-slide tour of every Phase 1 template.",
                dark_background=False,
                notes=(
                    "Welcome. This deck is generated by the local example script "
                    "and demonstrates every Phase 1 template Megadeck ships with."
                ),
                transition=TransitionKind.FADE,
            ),
            HeroStatementSlide(
                kind="hero_statement",
                eyebrow="Remember",
                statement="Hard is good.",
                supports=[
                    "Easy ideas get copied. Hard ideas have moats.",
                    "Stripe, SpaceX, Tesla — they all started from problems that looked too hard.",
                    "Don't chase the easy idea. Chase the painful problem.",
                ],
                notes=(
                    "Counter-intuitive truth: hard is good. Easy markets get crowded. "
                    "Hard problems become moats once you solve them."
                ),
                transition=TransitionKind.FADE,
            ),
            NumberedListSlide(
                kind="numbered_list",
                eyebrow="Founder Pitfalls",
                title="The 5 most common ways founders fail",
                subtitle="Patterns we see again and again across early-stage teams.",
                items=[
                    BulletItem(
                        head="Building in stealth.",
                        tail="Months of code, zero customer conversations, wrong product.",
                    ),
                    BulletItem(
                        head="Skipping pricing.",
                        tail="Free trials hide the truth. Charge from day one.",
                    ),
                    BulletItem(
                        head="Hiring too early.",
                        tail="Wrong hires cost six months. Stay tiny until customers pull you.",
                    ),
                    BulletItem(
                        head="Avoiding sales.",
                        tail="Sales is a learnable skill, not a personality trait.",
                    ),
                    BulletItem(
                        head="Optimizing the wrong thing.",
                        tail="Speed of code matters less than speed of learning.",
                    ),
                ],
                notes=(
                    "Five patterns. Each one is fixable. Each one kills startups when ignored."
                ),
                transition=TransitionKind.FADE,
            ),
            ThreeCardSlide(
                kind="three_card",
                eyebrow="How to Evaluate a Startup Idea",
                title="3 signs your idea is worth pursuing",
                subtitle="If your idea checks all three, the odds tilt your way.",
                items=[
                    CardItem(
                        badge="01",
                        label="Founder–market fit",
                        description=(
                            "You understand the customer better than almost anyone. "
                            "You bring an unfair advantage in execution."
                        ),
                    ),
                    CardItem(
                        badge="02",
                        label="A real, painful problem",
                        description=(
                            "You — or someone close to you — feel the pain every day. "
                            "You know exactly how much it costs."
                        ),
                    ),
                    CardItem(
                        badge="03",
                        label="A new, important insight",
                        description=(
                            "You see something the rest of the market has missed. "
                            "That insight is the wedge that opens the door."
                        ),
                    ),
                ],
                notes=(
                    "Three checks. Founder market fit, painful problem, fresh insight."
                ),
                transition=TransitionKind.FADE,
            ),
            TwoColumnSlide(
                kind="two_column",
                eyebrow="Stage 1 vs Stage 2",
                title="Do things that don't scale — until you have to scale",
                subtitle="The journey is two stages. Most founders mix them up.",
                left_title="Stage 1 — Don't scale",
                left_items=[
                    BulletItem(head="Recruit users one by one.", tail="Cold email, DMs, in-person."),
                    BulletItem(head="Onboard each user yourself.", tail="You learn what is broken faster."),
                    BulletItem(head="Pick channels narrow first.", tail="One niche where customers cluster."),
                    BulletItem(head="Talk to every user.", tail="Personally. By name. Weekly."),
                ],
                right_title="Stage 2 — Build the engine",
                right_items=[
                    BulletItem(head="Find one repeatable channel.", tail="Paid, content, partnerships, sales."),
                    BulletItem(head="Measure CAC and LTV honestly.", tail="If LTV/CAC > 3, scale that channel."),
                    BulletItem(head="Hire only after the channel works.", tail="Don't hire to find growth."),
                    BulletItem(head="Beware vanity metrics.", tail="Active paying users beat signups."),
                ],
                notes=(
                    "The two-stage pattern is the hardest mental model in customer acquisition."
                ),
                transition=TransitionKind.FADE,
            ),
        ],
    )


if __name__ == "__main__":
    deck = build_sample_deck()
    out = render_deck(deck, Path("megadeck-demo.pptx"))
    print(f"Wrote {out}")
