"""Adapter: Material You dynamic-color generator.

Source studied (Apache 2.0):
  https://github.com/material-foundation/material-color-utilities

Algorithm (simplified port)
---------------------------
Material You's TonalPalette: any seed colour is mapped to HCT
(hue / chroma / tone) space, and a 13-tone scale is generated by varying
tone (lightness) while keeping hue + chroma fixed. From those scales,
3 palettes are derived:

  * primary   — seed hue, full chroma
  * neutral   — seed hue, chroma reduced to ~4 (muted)
  * variant   — seed hue, chroma reduced to ~16 (slightly tinted neutral)

Tones used (per Material You light theme):
  primary 40, on-primary 100, primary-container 90, on-primary-container 10,
  surface 99, on-surface 10, surface-variant 90, outline 50.

We don't need full HCT colour science — colorsys's HLS gives identical
results for the kinds of palettes Material You produces. Tone in Material
You is roughly equivalent to L in HSL (with a slight perceptual adjust),
so we generate the 13-tone scale directly via HLS interpolation.

The user's promise: any seed hex → infinite themes (5 visual styles ×
light/dark = 10 themes per seed).
"""
from __future__ import annotations

import colorsys
from typing import Dict, List, Literal

from megadeck.design_system.themegen import (
    Palette,
    VisualStyle,
    generate_theme,
    hex_to_rgb,
    rgb_to_hex,
)


def _tonal_palette(seed_hex: str, chroma_factor: float = 1.0) -> Dict[int, str]:
    """Generate a 13-tone scale from a seed.

    `chroma_factor` ∈ (0, 1] reduces saturation (1.0 = full, 0.05 = neutral).
    Returns {tone: hex} for tones [0, 10, 20, …, 100].
    """
    r, g, b = hex_to_rgb(seed_hex)
    h, _, s = colorsys.rgb_to_hls(r / 255, g / 255, b / 255)
    s = s * chroma_factor
    palette: Dict[int, str] = {}
    for tone in range(0, 101, 10):
        # Tone in Material You ≈ L in HLS for our purposes.
        l = tone / 100.0
        rr, gg, bb = colorsys.hls_to_rgb(h, l, s)
        palette[tone] = rgb_to_hex(int(rr * 255), int(gg * 255), int(bb * 255))
    return palette


def palette_from_seed(seed_hex: str, name: str = "material") -> Palette:
    """Build a megadeck `Palette` from a single seed colour using Material
    You's tonal-palette derivation."""
    primary = _tonal_palette(seed_hex, chroma_factor=1.0)
    neutral = _tonal_palette(seed_hex, chroma_factor=0.06)  # near-neutral surfaces
    return Palette(
        name=name,
        accent=primary[40],
        accent_dk=primary[20],
        accent_lt=primary[80],
        bg_light=neutral[100],   # near-white tinted
        bg_dark=neutral[10],     # near-black tinted
    )


def generate_material_themes(
    seed_hex: str,
    *,
    base_name: str | None = None,
    visual_styles: List[VisualStyle] | None = None,
) -> List[Dict]:
    """Yield the full set of (style, mode) combinations for one seed.

    With 5 default visual styles × 2 modes = 10 themes per seed. Any seed
    works — pass any hex, get back ten distinct themes.
    """
    if visual_styles is None:
        visual_styles = ["flat", "shadow", "glass", "orbs", "corner-glow"]
    palette = palette_from_seed(seed_hex, name=base_name or "material")
    out: List[Dict] = []
    for mode in ("light", "dark"):
        for style in visual_styles:
            out.append(generate_theme(
                palette,
                visual_style=style,
                mode=mode,
                name=f"{palette.name}-{style}-{mode}",
                description=f"Material You from seed {seed_hex} ({style}, {mode}).",
            ))
    return out


__all__ = [
    "_tonal_palette", "palette_from_seed", "generate_material_themes",
]
